### ISSUE TITLE
Unable to build and start the project as i'm getting the following issue " TypeError: Cannot read property 'properties' of undefined"

### ISSUE THREAD

**Issue by QA2Dev** [aayusharora/GeneticAlgorithms#4]
I'm getting the following issue when I run build (npm run build) or start (npm run start) command in script block, as shown below.

**C:\Users\myuser\Documents\GeneticAlgorithms\part1>npm run build**

> chrome-dino-game@1.0.0 build C:\Users\myuser\Documents\GeneticAlgorithms\part1
> webpack --mode production

C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chrome-dino-game@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dino-game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2018-12-04T08_53_34_451Z-debug.log

**C:\Users\myuser\Documents\GeneticAlgorithms\part1>npm run start**

> chrome-dino-game@1.0.0 start C:\Users\myuser\Documents\GeneticAlgorithms\part1
> webpack-dev-server --mode development

C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (C:\Users\myuser\Documents\GeneticAlgorithms\part1\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chrome-dino-game@1.0.0 start: `webpack-dev-server --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dino-game@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2018-12-04T08_54_08_783Z-debug.log

**Comment by pratyush1687** [comment]
hey @QA2Dev  this is probably due to your webpack-cli and webpack-dev-server versions,
please update them to 
![image](https://user-images.githubusercontent.com/25077017/49922660-5dcdeb00-fed7-11e8-97bc-6c1cc36a9562.png)

**Comment by QA2Dev** [comment]
@pratyush1687 Thank you for response, I'm already using updated versions, but issue persists.

C:\Users\E004223\Documents\GeneticAlgorithms\part1>npm run build

> chrome-dino-game@1.0.0 build C:\Users\E004223\Documents\GeneticAlgorithms\part1
> webpack --mode production

C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chrome-dino-game@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dino-game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\E004223\AppData\Roaming\npm-cache\_logs\2018-12-13T12_44_40_052Z-debug.log

C:\Users\E004223\Documents\GeneticAlgorithms\part1>npm run start

> chrome-dino-game@1.0.0 start C:\Users\E004223\Documents\GeneticAlgorithms\part1
> webpack-dev-server --mode development

C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (C:\Users\E004223\Documents\GeneticAlgorithms\part1\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chrome-dino-game@1.0.0 start: `webpack-dev-server --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dino-game@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\E004223\AppData\Roaming\npm-cache\_logs\2018-12-13T12_46_57_681Z-debug.log

C:\Users\E004223\Documents\GeneticAlgorithms\part1>

**Comment by QA2Dev** [comment]
![image](https://user-images.githubusercontent.com/36038466/49940985-41e23d80-ff07-11e8-9d55-4b6b06479b47.png)

**Comment by pratyush1687** [comment]
can you try changing it to the same versions as mine?

**Comment by QA2Dev** [comment]
@pratyush1687 I tried with the same versions as you shown but I'm facing the same issue, later I changed versions to the latest and tried, issue persists.

**Comment by DragonEmperorG** [comment]
I solved my problem by manually installing "webpack-dev-server" dependency. And I removed the "dev" dependency to solve my `npm install` failing issue. You'd better confirm that your local webpack-dev-server installation is fine. After I ran `node_modules/.bin/webpack-dev-server` effectively, the `npm run start` script worked fine magically.
![image](https://user-images.githubusercontent.com/24807062/50394414-48d73e80-0798-11e9-89f3-a1fe85b31b8c.png)

![image](https://user-images.githubusercontent.com/24807062/50394335-d1091400-0797-11e9-9030-1f3896186da7.png)

**Comment by QA2Dev** [comment]
@pratyush1687 Though I tried with the versions you advised, issue persists

**Comment by pratyush1687** [comment]
did you try what @DragonEmperorG has done?

**Comment by aayusharora** [comment]
Closing due to inactivity. Kindly open again, if it has not been resolved.
